# Generated by Django 3.1.7 on 2021-03-08 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Experience', models.IntegerField(default=0)),
                ('Country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skill_name', models.CharField(max_length=200)),
                ('Skill_level', models.CharField(max_length=50)),
                ('Developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninjas.developer')),
            ],
        ),
    ]
